[build-system]
build-backend = 'mesonpy'
requires = ['meson-python', 'numpy>=2.0.0']

[project]
name = 'pyDISORT'
requires-python = '>=3.12'
version = '4.0.99'
readme = 'README.rst'
description = 'Run DISORT in Python!'
