# Upon a push to main, this workflow will:
# -- install pyDISORT
# -- test pyDISORT

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test-pyDISORT:
    name: "Test pyDISORT on ${{ matrix.os }} using Python ${{ matrix.python-version }} and ${{ matrix.toolchain.compiler }} version ${{ matrix.toolchain.version }}"

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-12, macos-13, macos-14]
        python-version: ["3.12"]
        toolchain:
          - {compiler: gcc, version: 13}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup GNU Fortran
        uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}

      - name: Install pyDISORT and testing utilities
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
          python -m pip install pytest

      - name: Test with pytest
        run: |
          python -m pytest .
